SamwaMoney/Timetable-Artist-front

- src/components/_common/CommentModal.jsx
- src/components/_common/EditModal.jsx
- src/components/_common/Hamburger.jsx
- src/components/_common/Hamburger.style.js
- src/components/_common/Modal.style.js
- src/components/_common/RankingModal.jsx
- src/components/_common/ResetModal.jsx
- src/components/_common/WithdrawalModal.jsx
- src/components/aboutuspage/AboutUs.jsx
- src/components/aboutuspage/AboutUs.style.js
- src/components/loginpage/Login.jsx
- src/components/loginpage/Login.style.js
- src/components/loginpage/signin/SignIn.jsx
- src/components/loginpage/signin/SignIn.style.js
- src/components/loginpage/signup/SignUp.jsx
- src/components/loginpage/signup/SignUp.style.js
- src/components/mainpage/Main.jsx
- src/components/mainpage/Main.style.js
- src/pages/AboutUsPage.jsx
- src/pages/LoginPage.jsx
- 반응형으로 수정 완료
- 메인 화면 제외 다른 화면에서 로고 이미지 `width: 18vw;`로 설정
- 넘치는 부분 overflow: hidden으로 설정
- 모달 사용 시 `setIs모달이름Open`으로 props 전달해 주세요.
- 반응형 확인 부탁드립니다.
> [Feat] 메인, 로그인, About Us, 햄버거, 모달 화면 퍼블리싱

- src/components/createpage/TimeTable.jsx
-  시간표 강의 추가 페이지에서 시간표 틀 생성했습니다. (Timetable.jsx)
-   조만간 강의 블록 생성 기능 추가하겠습니다
> feat: 시간표 틀 생성

- src/components/_common/Modal.style.js
- src/components/aboutuspage/AboutUs.jsx
- src/components/aboutuspage/AboutUs.style.js
- src/components/loginpage/Login.jsx
- src/components/loginpage/Login.style.js
- src/components/loginpage/signin/SignIn.style.js
- src/components/loginpage/signup/SignUp.style.js
- src/components/mainpage/Main.style.js
메인, 로그인, 소개 페이지와 모달을 반응형으로 수정했습니다.
%와 vw, vh를 사용했습니다.
반응형 CSS 확인 부탁드립니다.
> fix: 메인, 로그인, 소개 페이지 및 모달 반응형 수정

- package-lock.json
- package.json
- src/App.js
- src/components/_common/EditModal.jsx
- src/components/_common/M_Hamburder.jsx
- src/components/_common/M_Hamburger.jsx
- src/components/_common/M_Hamburger.style.js
- src/components/_common/M_HamburgerBtn.jsx
- src/components/_common/Modal.style.js
- src/components/_common/ResetModal.jsx
- src/components/rankingpage/M_Rank.jsx
- src/components/rankingpage/M_Ranking.style.js
- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/leftSection/Button.jsx
- src/components/rankingpage/leftSection/MyScore.jsx
- src/components/rankingpage/leftSection/OneRanking.jsx
- src/components/rankingpage/rightSection/CmtButton.jsx
- src/components/rankingpage/rightSection/HeartButton.jsx
- src/pages/404Page.jsx
- src/pages/M_MenuPage.jsx
- src/pages/RankingPage.jsx
- src/reducer/ranking.js
-   어떤 작업 수행했는지 (+필요하다면 스크린샷 첨부)
랭킹페이지와 메뉴 페이지의 앱 퍼블리싱을 하였습니다.
햄버거 버튼을 추가하였습니다. 모든 페이지에 이 햄버거 버튼이 필요할 것 같습니다!
> [Feat] 랭킹페이지, 메뉴페이지 앱 퍼블리싱

- src/components/_common/M_HamburgerBtn.jsx
- src/components/rankingpage/M_Rank.jsx
- src/components/rankingpage/M_Ranking.style.js
- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/leftSection/Button.jsx
- src/components/rankingpage/leftSection/MyScore.jsx
- src/components/rankingpage/leftSection/OneRanking.jsx
- src/components/rankingpage/leftSection/RankingList.jsx
- src/components/rankingpage/leftSection/Tab.jsx
- src/components/rankingpage/leftSection/Toggle.jsx
- src/components/rankingpage/rightSection/CmtButton.jsx
- src/components/rankingpage/rightSection/HeartButton.jsx
- src/components/rankingpage/rightSection/NewComment.jsx
- src/components/rankingpage/rightSection/OneComment.jsx
- src/components/rankingpage/rightSection/RankUserInfo.jsx
- src/pages/404Page.jsx
- src/pages/RankingPage.jsx
> [fix] 랭킹 앱 퍼블리싱 수정

- src/components/_common/BackBtn.jsx
- src/components/_common/M_Hamburger.jsx
- src/components/_common/M_Hamburger.style.js
- src/components/_common/M_HamburgerBtn.jsx
- src/components/aboutuspage/M_AboutUs.jsx
- src/components/aboutuspage/M_AboutUs.style.js
- src/components/rankingpage/M_Rank.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/leftSection/OneRanking.jsx
- src/components/rankingpage/leftSection/RankingList.jsx
> [Fix] 랭킹 앱 css 완성, 버튼 수정

- package-lock.json
- src/components/createpage/CreateTimeTable.jsx
- src/components/createpage/CreateTimeTable.style.js
- src/components/createpage/TimeTable.jsx
- src/components/createpage/TimeTableInput.jsx
- src/components/createpage/TimeTableInput.style.js
-  시간표 강의 추가 페이지 (createpage) 수정된 디자인 반영하여 퍼블리싱하였습니다.
-  반응형 구현하였습니다.
-   모바일 퍼블리싱은 토요일~일요일까지 작업할 예정이고, 시간표 기능 구현 (강의 추가) 부분은 월요일~화요일까지 완성하도록 하겠습니다.
> fix: createpage 수정된 디자인 반영, 반응형 추가

- src/components/_common/BackBtn.jsx
- src/components/rankingpage/M_RankDetail.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/rightSection/CmtButton.jsx
- src/components/rankingpage/rightSection/CommentList.jsx
- src/components/rankingpage/rightSection/HeartButton.jsx
- src/components/rankingpage/rightSection/NewComment.jsx
- src/components/rankingpage/rightSection/OneComment.jsx
> [Fix] 랭킹 디테일 css 완성

- src/components/_common/M_Hamburger.jsx
- src/components/scorepage/M_Score.jsx
- src/components/scorepage/M_Score.style.js
- src/components/scorepage/M_ScoreHamburgerBtn.jsx
- 햄버거 버튼 상단 고정 없도록 수정 (점수 페이지만)
- no data 모바일 시간표 점수 화면 추가
- border 더 얇게 수정
-   모바일 border 0.05rem으로 수정합시다~
> feat: 모바일 시간표 점수 페이지 no data 화면 추가 및 border, 햄버거 수정

- package-lock.json
- package.json
- src/components/createpage/TimeTable.jsx
- src/components/createpage/TimeTableInput.jsx
- src/reducer/action.js
- src/reducer/index.js
- src/reducer/timetable.js
- src/store/store.js
-   timetable 관련 redux 관련 함수와 파일 추가하였습니다.
- TimeTable.jsx에 강의 추가 기능 구현하였습니다. (PC only)
-   강의 추가 기능은 간이로 제작한 것이고, 하드코딩 된 부분이 있어 다시 수정해야할 것 같습니다.
- redux process 파악을 위해서 `redux-devtools-extension` 라이브러리를 추가하였습니다. pull 받으실 때 `npm install redux-devtools-extension` 입력해주시면 좋을 것 같아요.
> feat: timetable redux 파일 추가 및 강의 추가 기능 구현

- src/components/createpage/M_CreateTimeTable.style.js
- src/components/createpage/TimeTable.jsx
-   시간표 강의 추가 페이지 PC 초기화-시간표 컴포넌트 짤림 이슈 해결
-  모바일 border 굵기 수정
-   추후 반응형 이상한 거 있으면 알려주세요
> fix: 시간표 강의 추가 PC 페이지 오류 수정, 모바일 border 수정

- src/components/_common/Modal.style.js
- src/components/loginpage/signin/SignIn.style.js
- src/components/loginpage/signup/SignUp.style.js
- src/components/mainpage/M_Main.style.js
-  모달을 디자인과 유사하게 수정했습니다.
- 모바일 css 수정을 했습니다
> [Fix] 모달 css 수정 및 모바일 border 수정

- src/api/ranking.api.js
- src/api/ranking.js
- src/api/timetables.js
- src/components/rankingpage/Ranking.style.js
> [Feat] 랭킹보드 기본api 추가

- src/components/createpage/TimeTableClassCell.jsx
- src/components/createpage/TimeTableInput.jsx
-   지정된시간없음 체크 시 null로 표시
-   오류 수정해서 이번주까지 푸시하겠습니다
> [Feat] 시간표 강의 추가 페이지 지정된시간없음 null로 수정

- src/components/createpage/TimeTableInput.jsx
-   PC버전 input 부분 강의 이름 입력창에서 enter키 클릭 시 강의 추가 기능 실행되도록 코드 추가하였습니다.
-   강의 삭제 기능 현재 구현 중인데 내일 밤까지 추가할게요!
-  모바일 부분은 PC버전 다 완성되면 추가하겠습니다!
> [Feat] 시간표 강의 추가 input 부분 엔터 키 클릭 시 제출 기능 추가

- src/components/_common/DeleteConfirmModal.jsx
- src/components/_common/DeleteNoticeModal.jsx
- src/components/createpage/TimeTable.jsx
- src/components/createpage/TimeTableCell.jsx
- src/components/createpage/TimeTableRow.jsx
-   TimeTable.jsx, TimeTableRow.jsx, TimeTableCell.jsx가 시간표를 구성하는 컴포넌트입니다.
-  렌더링을 줄이기 위해 상위 컴포넌트인 TimeTable.jsx에서 redux timetable 데이터를 가져온 뒤, 하위 컴포넌트 TimeTableRow.jsx에 전달한 뒤, 데이터를 가공하여 그 하위 컴포넌트인 TimeTableCell.jsx에 전달하도록 수정했습니다.
-  redux timetable 데이터에 수정사항이 생기면 다시 갱신하도록 TimeTable.jsx에 useEffect 관련 코드를 추가하였습니다.
- 삭제 관련 모달 2개 (삭제하시겠습니까?, 삭제하였습니다) 모달을 2개로 분리하여 관리가 용이하도록 하였습니다.
-   초기화 관련 기능 추가한 뒤, 모바일에도 코드 적용하도록 하겠습니다.
-  createpage api 관련 작업은 다음 주 초반쯤에 진행할 것 같습니다.
> [Feat] createpage 삭제 기능 구현

- src/components/createpage/DateTimeDropdown.jsx
- src/components/createpage/M_TimePicker.jsx
- src/components/createpage/M_TimeTableInputModal.jsx
- src/components/createpage/TimeTable.jsx
- src/components/createpage/TimeTableCell.jsx
- src/components/createpage/TimeTableInput.jsx
- src/components/createpage/TimeTableRow.jsx
- src/reducer/timetable.js
- src/utils/time-helper.js
- src/utils/time-validation.js
-   시간표 완성 클릭 시 보내야 할 키 명이 day, place, name이 아니라 weekday, location, className 으로 되어있더라고요..
-  그래서 시간표 관련 모든 파일에서 key 명을 전부 위와 같이 변경했습니다. 
- (시간표 완성 버튼 클릭 시 변경할 경우 불필요한 로직이 들어가게 되어서 이번에 싹 다 바꾸는게 나을 것 같다는 생각이 들었습니다)
-   이름 수정 후 PC, 모바일 화면 상 ui나 기능에 문제가 없음을 확인했으나, 시간 유효성 코드나 일부 모바일 input 코드는 제가 짠 부분이 아니기에 일부 오류가 있을 가능성이 있습니다. 수정된 코드 확인 부탁드리고자 혜린님 리뷰어로 태그했습니다!
> [Fix] timetable redux 데이터 키명 변경

- src/components/_common/DeleteCmtConfirmModal.jsx
- src/components/_common/DeleteNoticeModal.jsx
- src/components/rankingpage/M_RankDetail.jsx
- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/RankDetail.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/rightSection/CommentList.jsx
- src/components/rankingpage/rightSection/NewComment.jsx
- src/components/rankingpage/rightSection/OneComment.jsx
- src/components/rankingpage/rightSection/RankUserInfo.jsx
- src/reducer/index.js
- src/reducer/myInfo.js
- src/skeleton/MDetailSectionSkeleton.jsx
- src/skeleton/MRankingListSkeleton.jsx
- src/skeleton/RankingListSkeleton.jsx
- src/skeleton/RightSectionSkeleton.jsx
- src/skeleton/skeleton.style.js
> [Fix] 리덕스 명 수정

- src/components/_common/Loading.jsx
- src/reducer/action.js
- src/reducer/myInfo.js
> [Feat] myInfo 리덕스 코드 추가

- src/api/timetables.js
- src/components/createpage/TimeTableInput.jsx
-   수업 생성 api 연결 완료하였습니다.
-  시간표 완성 버튼을 누르면 강의 데이터 배열이 서버로 보내지며, 결과 페이지로 이동하게 됩니다.
-   timetableId 관련 로직이 햄버거바에서 진행되다보니, 태영님께서 시간표 생성과 삭제 api 연결을 맡아주시기로 했습니다.
-  현재 제 코드는 timetableId를 하드코딩하여 1로 설정하고 짰기 때문에 추후 수정이 필요합니다.
-  모바일의 경우에는 PC 버전 코드가 다 완성되면 작업을 진행하고자 합니다.
> [Feat] createpage PC 버전 수업 생성 api 연결

- src/api/scores.js
- src/api/test.js
- src/components/scorepage/Score.jsx
> [Feat] 랭킹보드 게시 api 연결

- src/api/timetables.js
- src/components/_common/EditModal.jsx
-  시간표 삭제 api url 패턴을 `/timetables/{table_id}/{member_id}`로 하니 제대로 동작해서 업데이트 했습니다.
현재 댓글이 있는 시간표는 삭제가 안 되니 유의해 주세요.
> [Fix] 시간표 삭제 api 수정

- src/components/_common/DeleteCmtConfirmModal.jsx
- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/leftSection/MyScore.jsx
- src/components/rankingpage/leftSection/OneRanking.jsx
- src/components/rankingpage/rightSection/OneComment.jsx
> [Fix] 댓글 삭제 기능 수정

- src/components/rankingpage/rightSection/CmtLikeBtn.jsx
- src/components/rankingpage/rightSection/LikeBtn.jsx
- src/components/rankingpage/rightSection/NewComment.jsx
- src/components/rankingpage/rightSection/OneComment.jsx
> [Fix] 좋아요 수정

- src/components/createpage/CreateTimeTable.jsx
- src/components/createpage/M_CreateTimeTable.jsx
- src/components/createpage/TimeTable.jsx
- src/components/createpage/TimeTableCell.jsx
- src/components/createpage/TimeTableRow.jsx
- src/components/scorepage/M_Score.jsx
- src/components/scorepage/Score.jsx
-   TimeTable 컴포넌트 isHidden props 추가 (isHidden이 true일 때 강의명이 가려짐)
-  isScorePage props 자료형 String 형태에서 Boolean 형태로 변경 ("true"가 아니라 true일 때 적용됨 - 이와 관련된 컴포넌트 전부 수정)
-   곧 classList props도 추가하겠습니다
> [Feat] TimeTable 컴포넌트 isHidden props 추가

- src/components/createpage/TimeTableInput.jsx
-   시간표 완성 클릭 시 강의 시간이 null인 경우 오류가 발생 -> if문 추가하여 수정함
-
> [Fix] createpage input 강의시간 null일 경우 오류 수정

- src/components/createpage/CreateTimeTable.jsx
- src/components/createpage/M_CreateTimeTable.jsx
- src/components/createpage/TimeTable.jsx
-   TimeTable에서 isScorePage가 true일 때 classList 데이터를 띄워주도록 추가했습니다
-   같은 강의이름을 가진 데이터를 같은 배경색으로 표시해주는 부분은 아직 구현이 안된 상태로, 이 부분 백엔드 팀원분께 여쭤보고 안되면 제가 관련 코드 추가하겠습니다.
> [Feat] scorepage용 TimeTable 컴포넌트 데이터 연결

- src/components/_common/M_Loading.jsx
- src/components/_common/M_ScoreLoading.jsx
- src/components/_common/ScoreLoading.jsx
- src/components/rankingpage/M_Rank.jsx
- src/components/rankingpage/M_RankDetail.jsx
- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/RankDetail.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/leftSection/MyScore.jsx
- src/components/rankingpage/rightSection/CmtTag.jsx
- src/components/rankingpage/rightSection/LikeBtn.jsx
- src/components/scorepage/Score.jsx
- src/pages/RankingPage.jsx
- src/skeleton/RightSectionSkeleton.jsx
-   어떤 작업 수행했는지 (+필요하다면 스크린샷 첨부)
> [Feat] 채점 로딩페이지 제작

- src/components/_common/EditModal.jsx
-   EditModal.js 파일에 옵셔널 체이닝을 추가해서 에러를 처리했습니다.
> [Fix] 시간표 삭제 오류 처리 수정

- src/components/_common/ResetModal.jsx
- src/components/createpage/CreateTimeTable.jsx
- src/components/createpage/M_CreateTimeTable.jsx
- src/components/createpage/TimeTable.jsx
- src/reducer/action.js
- src/reducer/timetable.js
-   초기화 버튼 구현했습니다
-  초기화 버튼 클릭 시 redux action 함수를 통해 selectedData에 있는 데이터가 빈 배열로 초기화됩니다.
-
> [Feat] createpage 초기화 버튼 기능 구현

- README.md
- src/components/_common/EditModal.jsx
- src/components/rankingpage/M_Rank.jsx
- src/components/rankingpage/M_RankDetail.jsx
- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/RankDetail.jsx
- src/components/rankingpage/Ranking.style.js
- src/components/rankingpage/leftSection/MyScore.jsx
- src/components/rankingpage/leftSection/Tab.jsx
- src/components/rankingpage/rightSection/CmtLikeBtn.jsx
- src/components/rankingpage/rightSection/CommentList.jsx
- src/components/rankingpage/rightSection/NewComment.jsx
- src/skeleton/RankingListSkeleton.jsx
> [Feat] 리드미 기능설명 추가

- src/components/createpage/M_CreateTimeTable.jsx
- src/components/createpage/M_TimeTableInputModal.jsx
- src/components/createpage/TimeTable.jsx
- src/components/createpage/TimeTableCell.jsx
- src/components/createpage/TimeTableInput.jsx
-   createpage에 사용되는 시간표 완성 함수에서 배경색 프로퍼티 제출을 추가하였습니다.
-  createpage 모바일 `완성` 버튼에 시간표 완성 제출 함수를 달아두었습니다.
-   모바일에 username 적용, 시간표 완성 클릭 시 로딩 모달 띄우기 작업은 오늘 밤까지 완료하겠습니다.
> [Feat] createpage PC/모바일 수업 생성 api 배경색 추가, 모바일에 시간표 완성 함수 적용

- src/components/loginpage/signup/SignUp.jsx
- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/RankDetail.jsx
- src/components/rankingpage/rightSection/CmtLikeBtn.jsx
- src/components/rankingpage/rightSection/CommentList.jsx
- src/components/rankingpage/rightSection/LikeBtn.jsx
- src/components/rankingpage/rightSection/OneComment.jsx
> [Fix] 좋아요 이후 랭킹 불러오기 기능 수정

- src/components/createpage/Dropdown.style.js
- src/components/createpage/TimeTable.jsx
-   createpage TimeTable 컴포넌트, Input 컴포넌트 ui 수정
-   ui 확인 부탁드립니다!
> [Fix] createpage TimeTable 컴포넌트, Input 컴포넌트 ui 수정

- src/components/scorepage/M_Score.jsx
- src/components/scorepage/Score.jsx
> [Fix] 점수 페이지 isHidden 초기값 변경

- src/components/rankingpage/Rank.jsx
- src/components/rankingpage/RankDetail.jsx
> [Fix] 랭킹 로딩 수정

- src/components/createpage/M_CreateTimeTable.jsx
> [Feat] createpage 모바일 username 추가

- src/components/createpage/CreateTimeTable.jsx
- src/components/createpage/TimeTableInput.jsx
-   로딩 발생 시 로딩 컴포넌트가 뜨도록 추가했습니다.
- 시간표 완성 버튼 클릭 시 redux 데이터가 초기화되도록 수정했습니다.
-   곧 모바일 수정하겠습니다.
> fix: createpage PC 로딩 추가 & 시간표 완성 시 redux 데이터 초기화 추가

- src/components/createpage/M_CreateTimeTable.jsx
- src/components/createpage/M_CreateTimeTable.style.js
- src/components/createpage/TimeTable.jsx
> [Feat] createpage 모바일 로딩 페이지 추가

- src/components/rankingpage/rightSection/CommentList.jsx
- src/skeleton/MDetailSectionSkeleton.jsx
> [Fix] 모바일 랭킹 css  수정

- src/components/createpage/TimeTable.jsx
-   TimeTable 컴포넌트 tbody style 관련 코드 삭제
> [Fix] TimeTable 컴포넌트 tbody style 관련 코드 삭제
